packages: []
catalogs:
  build:
    '@iconify-json/carbon': ^1.2.8
    '@vitejs/plugin-vue': ^5.2.3
    jsdom: ^26.1.0
    unocss: ^66.1.0
    unplugin: ^2.3.2
    unplugin-auto-import: ^19.1.2
    unplugin-vue-components: ^28.5.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
    '@iconify/tailwind4': ^1.0.6
    unplugin-icons: ^22.1.0
    vite-plugin-vue-devtools: 1.0.0-rc.5
  dev:
    '@eonova/eslint-config': ^0.3.1
    '@types/node': ^22.15.11
    '@unocss/eslint-plugin': ^66.1.0
    '@vue-macros/volar': ^3.0.0-beta.10
    '@vue/test-utils': ^2.4.6
    eslint: ^9.26.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.1
    simple-git-hooks: ^2.13.0
    taze: ^19.0.4
    typescript: ^5.8.3
    vitest: ^3.1.3
    vue-tsc: ^2.2.10
    '@alova/adapter-axios': ^2.0.13
    '@typescript-eslint/eslint-plugin': ^8.32.1
    '@typescript-eslint/parser': ^8.32.1
    cspell: ^9.0.2
    dotenv: ^16.5.0
    eslint-define-config: ^2.1.0
    knip: ^5.58.0
    pinia: ^3.0.2
    pinia-auto-refs: ^0.0.12
    pinia-plugin-persistedstate: ^4.3.0
  frontend:
    '@vueuse/core': ^13.1.0
    vue: ^3.5.13
    vue-router: ^4.5.1
    alova: ^3.2.11
    daisyui: ^5.0.37
    '@ameinhardt/unocss-preset-daisy': ^1.1.7
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
